config/routes.rb
Rails.application.routes.draw do
  
  get 'relationships/create'
  get 'relationships/destroy'
  resources :lists
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'

  root to: 'lists#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :content, presence: true, length: { maximum: 255 }
  validates :store_name, :menu, :location, presence: true, length: { maximum: 30 }
  #has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :lists ,inverse_of: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @lists = List.all
  end

  
  def show
    @user = User.find_by(id: @list.user_id)
  end

  def new
    @list = current_user.lists.build()
  end

  def edit
    @list = List.find_by(id: params[:id])
  end


  def create
    @list = current_user.lists.build(list_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:store_name, :menu, :point, :content, :image, :location)
    end

    
    def correct_user
      @list = current_user.lists.find_by(id: params[:id])
      unless @list
        redirect_to root_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to '/'
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
   private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
  
      session[:user_id] = @user.id
      return true
    else
      
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to '/'
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>

  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      
<% model.errors.full_messages.each do |message| %>

        <li>
<%= message %>
</li>
      
<% end %>

    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">ラーメン口コミ</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item"><%= link_to 'ユーザー', users_path, class: 'nav-link' %>
　　　　</li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
        <ul class="dropdown-menu dropdown-menu-right">
          <li class="dropdown-item"><%= link_to 'マイプロフィール', user_path(current_user) %></li>
          <li class="dropdown-divider"></li>              　　　　
          <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
        </ul>
        </li>
        
      <% else %>

        <li class="nav-item">
            <%= link_to '会員登録', signup_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to 'ログイン', login_path, class: 'nav-link' %>
        </li>
      <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ラーメン口コミ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body style="margin: 0;">
  <%= render 'layouts/navbar' %>
    <div class="container">
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :店名 %>
    <%= form.text_field :store_name %>
  </div>

  <div class="field">
    <%= form.label :メニュー %>
    <%= form.text_field :menu %>
  </div>

<div class="field">
    <%= form.label :評価 %>
    <%=  form.select :point, ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], :prompt => "選択してください" %>
  </div>

  <div class="field">
    <%= form.label :説明 %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :写真 %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :場所 %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>口コミを編集</h1>

<%= render 'form', list: @list %>

<%= link_to '詳細', @list %> |
<%= link_to '戻る', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

    <h2>ラーメン店　口コミ一覧</h2>
    <br>
    <u><h5 class="text-right"><%= link_to '新規作成', new_list_path %></h5></u>
    <br>
    <br>
    <div class="container">
      <div class="row">
        <% @lists.each do |list| %>
        <div class="col-xl-4 col-md-6">
          <br>
          <div><%= image_tag list.image.to_s,{ width: 320, height: 240 } %></div>
          <br>
          <br>
          <h5>店名 ：　<%= list.store_name %></h5>
          <h5>評価 ：　<%= list.point %></5>
          <br>
          <br>
          <div class="d-flex justify-content-start">
            <u><h6><%= link_to '詳細を見る', list %></h6></u>　
            <% if list.user == current_user %>
            <u><h6><%= link_to '編集', edit_list_path(list) %></h6></u>　
            <u><h6><%= link_to '削除', list, method: :delete, data: { confirm: 'Are you sure?' } %></h6></u>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    

app/views/lists/new.html.erb
<h1>新規作成</h1>

<%= render 'form', list: @list %>

<%= link_to '戻る', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <br>
        <%= image_tag @list.image.to_s,{ width: 320, height: 240 } %>
    </div>
    <div class="offset-md-1 col-md-5 text-left">
      
      <p>
        <h5>投稿者 : <%= @user.name %></h5>
      </p>
    
      <p>
        <h5>店名 : <%= @list.store_name %></h5>
      </p>
      
      <p>
        <h5>メニュー : <%= @list.menu %></h5>
      </p>
      
      <p>
        <h5>評価 : <%= @list.point %></h5>
      </p>
      
      <p>
        <h5>説明 : <%= @list.content %></h5>
      </p>
      
      <p>
        <h5>場所 : <%= @list.location %></h5>
      </p>
      <br>
      <br>
        <h6 class="text-right">
          <% if @list.user == current_user %>
          <u><%= link_to '編集', edit_list_path(@list) %></u>
          <% end %>
          <u><%= link_to '戻る', lists_path %></u>
        </h6>
      </u>
    </div>
  </div>
</div>

app/views/users/_users.html.erb
<% if users.any? %>
  <div class="container">
    <div class="row">
      <% @users.each do |user| %>
        <div class="col-xl-4 col-md-6">
          <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 180 }) %>" alt="">
          <br>
          <br>
          <h5><%= user.name %></h5>
      　　<h6><%= link_to "プロフィールを見る", user_path(user) %></h6>
    　　</div>
      <% end %>
    </div>
  </div>
<%= paginate users %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h2>会員登録</h2>
</div>
<br>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
  <%= form_with(model: @user, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  
    <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
    <%= f.label :password_confirmation, 'パスワードの確認' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

  <%= f.submit '会員登録', class: 'btn btn-dark btn-block' %>
  <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div>
  <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 100 }) %>" alt="">
  <br>
  <br>
  <h5>ユーザー名 : <%= @user.name %></h5>
</div>
  <br>
  <br>
<div class="container">
  <div class="row">
    <% @user.lists.each do |list| %>
    <div class="col-xl-4 col-md-6">
      <br>
      <div><%= image_tag list.image.to_s,{ width: 240, height: 160 } %></div>
      <br>
      <h4>店名 ：　<%= list.store_name %></h4>
      <h4>評価 ：　<%= list.point %></h4>
      <br>
      <div><%= link_to '詳細を見る', list %></div>
      <br>
    </div>
    <% end %>
  </div>
</div>